# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: ERC4337 UserOp Indexer
contracts:
- name: EntryPointV07
  handler: src/EntryPoint.ts
  events:
  - event: UserOperationEvent(bytes32 indexed userOpHash, address indexed sender, address indexed paymaster, uint256 nonce, bool success, uint256 actualGasCost, uint256 actualGasUsed)
- name: EntryPointV06
  handler: src/EntryPoint.ts
  events:
  - event: UserOperationEvent(bytes32 indexed userOpHash, address indexed sender, address indexed paymaster, uint256 nonce, bool success, uint256 actualGasCost, uint256 actualGasUsed)
networks:
- id: 1
  start_block: 19274877
  contracts:
  - name: EntryPointV07
    address:
    - '0x0000000071727De22E5E9d8BAf0edAc6f37da032'
  - name: EntryPointV06
    address:
    - '0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789'
- id: 10
  start_block: 116453058
  contracts:
  - name: EntryPointV07
    address:
    - '0x0000000071727De22E5E9d8BAf0edAc6f37da032'
  - name: EntryPointV06
    address:
    - '0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789'
- id: 137
  start_block: 53784988
  contracts:
  - name: EntryPointV07
    address:
    - '0x0000000071727De22E5E9d8BAf0edAc6f37da032'
  - name: EntryPointV06
    address:
    - '0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789'
- id: 8453
  start_block: 10920348
  contracts:
  - name: EntryPointV07
    address:
    - '0x0000000071727De22E5E9d8BAf0edAc6f37da032'
  - name: EntryPointV06
    address:
    - '0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789'
- id: 42161
  start_block: 182947891
  contracts:
  - name: EntryPointV07
    address:
    - '0x0000000071727De22E5E9d8BAf0edAc6f37da032'
  - name: EntryPointV06
    address:
    - '0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789'
- id: 11155111
  start_block: 8668175
  contracts:
  - name: EntryPointV07
    address:
    - '0x0000000071727De22E5E9d8BAf0edAc6f37da032'
  - name: EntryPointV06
    address:
    - '0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789'
unordered_multichain_mode: true
rollback_on_reorg: false
field_selection:
  transaction_fields:
    - hash
